title: Datum Brain's Blog
email: info@datumbrain.com
description: >-
  Datum Brain's official blog.
baseurl: ""
url: "https://datumbrain.com"
twitter_username: datumbrain
github_username:  datumbrain

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
